-- MySQL Script generated by MySQL Workbench
-- Sun Feb  8 01:49:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema registry_engine
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `registry_engine` ;

-- -----------------------------------------------------
-- Schema registry_engine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registry_engine` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `registry_engine` ;

-- -----------------------------------------------------
-- Table `iconcaptcha_attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iconcaptcha_attempts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `iconcaptcha_attempts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARBINARY(16) NOT NULL,
  `attempts` INT NOT NULL,
  `timeout_until` DATETIME NULL,
  `valid_until` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `iconcaptcha_attempts_ip_address` ON `iconcaptcha_attempts` (`ip_address` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `iconcaptcha_challenges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iconcaptcha_challenges` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `iconcaptcha_challenges` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `challenge_id` VARCHAR(36) NOT NULL,
  `widget_id` VARCHAR(36) NOT NULL,
  `puzzle` TEXT NOT NULL,
  `ip_address` VARBINARY(16) NOT NULL,
  `expires_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `sessions_widget_challenge` ON `iconcaptcha_challenges` (`challenge_id` ASC, `widget_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `table1` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `table1` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
