-- MySQL Script generated by MySQL Workbench
-- Sun Mar 22 13:23:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema registry_engine
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `registry_engine` ;

-- -----------------------------------------------------
-- Schema registry_engine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registry_engine` DEFAULT CHARACTER SET utf8mb3 ;
SHOW WARNINGS;
USE `registry_engine` ;

-- -----------------------------------------------------
-- Table `geo_ip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geo_ip` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `geo_ip` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ipaddress` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `geo_ip` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ipaddress_UNIQUE` ON `geo_ip` (`ipaddress` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `iconcaptcha_attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iconcaptcha_attempts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `iconcaptcha_attempts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARBINARY(16) NOT NULL,
  `attempts` INT NOT NULL,
  `timeout_until` DATETIME NULL DEFAULT NULL,
  `valid_until` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE UNIQUE INDEX `iconcaptcha_attempts_ip_address` ON `iconcaptcha_attempts` (`ip_address` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `iconcaptcha_challenges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iconcaptcha_challenges` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `iconcaptcha_challenges` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `challenge_id` VARCHAR(36) NOT NULL,
  `widget_id` VARCHAR(36) NOT NULL,
  `puzzle` TEXT NOT NULL,
  `ip_address` VARBINARY(16) NOT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE UNIQUE INDEX `sessions_widget_challenge` ON `iconcaptcha_challenges` (`challenge_id` ASC, `widget_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invoice` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `invoice` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subscribe_id` INT UNSIGNED NOT NULL COMMENT 'reference to the subscription transaction details',
  `user_id` INT UNSIGNED NOT NULL COMMENT 'reference to the user table',
  `tax_id` VARCHAR(45) NOT NULL COMMENT 'Taxpayer Identification Number (Tax ID)',
  `vat_special` INT NOT NULL DEFAULT '1' COMMENT 'is VAT Special Invoice? zero means VAT Ordinary Invoice',
  `title` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL COMMENT 'e-mail address or mailing address',
  `phone_number` VARCHAR(20) NOT NULL,
  `bank_name` VARCHAR(45) NOT NULL DEFAULT '-',
  `bank_account` VARCHAR(45) NOT NULL DEFAULT '-',
  `add_time` DATETIME NOT NULL,
  `note` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `invoice` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_source_idx` ON `invoice` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `subscription_package_idx` ON `invoice` (`subscribe_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `invoice_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invoice_transaction` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `invoice_transaction` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `invoice_id` INT UNSIGNED NOT NULL,
  `subscription_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Multiple orders can be merged for invoice issuance.';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `invoice_transaction` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `subscription_idx` ON `invoice_transaction` (`subscription_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `invoice_id_idx` ON `invoice_transaction` (`invoice_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `search_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `search_history` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `search_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `q` VARCHAR(1024) NOT NULL,
  `hashcode` CHAR(32) NOT NULL,
  `session_id` VARCHAR(45) NOT NULL DEFAULT '-',
  `user_id` INT UNSIGNED NOT NULL,
  `ipaddress` VARCHAR(64) NOT NULL,
  `geo` INT UNSIGNED NOT NULL DEFAULT 0,
  `add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 65
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `search_history` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_obj_idx` ON `search_history` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `hash_index` ON `search_history` (`hashcode` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `geo_location_idx` ON `search_history` (`geo` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `search_hits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `search_hits` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `search_hits` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `symbol_id` INT UNSIGNED NOT NULL,
  `term` VARCHAR(2048) NOT NULL,
  `hashcode` CHAR(32) NOT NULL,
  `type_id` INT UNSIGNED NOT NULL,
  `hits` INT UNSIGNED NOT NULL DEFAULT '0',
  `add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `search_hits` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `hash_index` ON `search_hits` (`hashcode` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `search_hits` (`term`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `subscription` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `subscription` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `package` VARCHAR(45) NOT NULL,
  `amount` DECIMAL UNSIGNED NOT NULL DEFAULT 0,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `note` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `subscription` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_action_idx` ON `subscription` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL COMMENT 'user name, could be in any chars',
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL COMMENT 'password_hash result',
  `affiliation` VARCHAR(255) NOT NULL DEFAULT '-' COMMENT 'institution',
  `banned` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'has been banned from access the database resource?',
  `activated` INT NOT NULL DEFAULT '0' COMMENT 'verified of the user email?',
  `activate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'The activation time of the email account is mainly used to calculate the time difference, in order to implement an annual verification and activation mechanism for the account\'s email address.',
  `add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time of this user account',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `user` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_account` ON `user` (`email` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
